### ISSUE TITLE
__requireContext is not defined

### ISSUE THREAD

**Issue by xiaohuoni** [smrq/babel-plugin-require-context-hook#3]
"@babel/core": "^7.0.0",
work in a babel preset
```
export default function(context, opts = {}) {
  const plugins = [
    require.resolve('babel-plugin-require-context-hook'),
  ];

  return {
    presets: [
    ],
    plugins,
  };
}
```

Error:__requireContext is not defined

**Comment by smrq** [comment]
You also have to register the plugin in your code, as in the readme. This
behavior is what will happen if you only configure the plugin in your
babelrc.

**Comment by xiaohuoni** [comment]
thanks!I'm already register the plugin in the code

```
require('@babel/register')({
      presets: [babelPreset],
      only,
      ignore,
      babelrc: false,
      cache: false,
    });
```

**Comment by eddiemonge** [comment]
Do you have this: 
`require('babel-plugin-require-context-hook/register')()` somewhere?

**Comment by doniisetiiawan** [comment]
Hallo, how to solve this problem?

**Comment by kaorukobo** [comment]
> @eddiemonge 
> require('babel-plugin-require-context-hook/register')() 

That's the key. 
I could fix the error by adding the above line preceding use of `context.require`.

**Comment by fixotech** [comment]
> 
require.context
