### ISSUE TITLE
__requireContext is not defined. Babel 7/6 storybook

### ISSUE THREAD

**Issue by eddiemonge** [smrq/babel-plugin-require-context-hook#4]
```
    ReferenceError: __requireContext is not defined

       5 | import { withKnobs } from '@storybook/addon-knobs'
       6 |
    >  7 | const req = require.context('../components', true, /.?stories.jsx?$/)
         |          ^
       8 | function loadStories() {
       9 |   req.keys().forEach(filename => req(filename))
      10 | }
```

![context](https://user-images.githubusercontent.com/127535/47053243-ebec5600-d160-11e8-963c-e5b9cc22399b.png)

**Comment by eddiemonge** [comment]
I had to add

```
if (process.env.NODE_ENV === 'test') {
  require('babel-plugin-require-context-hook/register')()
}
```
to the storybook/config file as having it in jest/config didn't work.

I don't know if that is a bug here or in Jest or in Babel or a bug at all.

**Comment by bob76828** [comment]
I have the same problem for this.
Does anyone can help us?

**Comment by bob76828** [comment]
@eddiemonge I solved it.
I created a jest_setup.js in my .storybook folder for jest and wrote the code below as
```
import registerRequireContextHook from 'babel-plugin-require-context-hook/register';
registerRequireContextHook();
```
And last, I added the config
```
setupFiles: [
    './.storybook/jest_setup.js'
  ]
```
in my jest.config.js

**Comment by eddiemonge** [comment]
@bob76828 That worked. That's the part I was not understanding. when I read put it in jests setup file, I thought it meant its config, not its actual `setupFiles`
